# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network_communication.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'network_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bnetwork_communication.proto\x12\tfederated\"P\n\x0cModelWeights\x12\x16\n\x0eweights_matrix\x18\x01 \x01(\x0c\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\x15\n\rcurrent_round\x18\x03 \x01(\x05\":\n\x0f\x41\x63knowledgement\x12\x16\n\x0estatus_message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32Y\n\x11ModelOrchestrator\x12\x44\n\rStreamWeights\x12\x17.federated.ModelWeights\x1a\x1a.federated.Acknowledgementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELWEIGHTS']._serialized_start=42
  _globals['_MODELWEIGHTS']._serialized_end=122
  _globals['_ACKNOWLEDGEMENT']._serialized_start=124
  _globals['_ACKNOWLEDGEMENT']._serialized_end=182
  _globals['_MODELORCHESTRATOR']._serialized_start=184
  _globals['_MODELORCHESTRATOR']._serialized_end=273
# @@protoc_insertion_point(module_scope)
